In [1]:
f = open("text13012022.txt", "w")
print(f)

<_io.TextIOWrapper name='text13012022.txt' mode='w' encoding='cp1254'>


In [2]:
f.write("Now is the time")
f.write(" to close the file")

f.close()

In [3]:
f = open("text13012022.txt", "r")
text = f.read()
print(text)

Now is the time to close the file


In [4]:
f = open("text13012022.txt", "r")
print(f.read(9))

Now is th


In [5]:
print(f.read(1000006))

e time to close the file


In [7]:
fo = open("foo1301.txt", "w")
fo.write("Python is a great language.\nYeah its great!!\n")
fo.close()

In [8]:
fo = open("foo1301.txt", "r+")
mystr1 = fo.read(17)
print("Our string is : ", mystr1)

Our string is :  Python is a great


In [9]:
position = fo.tell()
print("Current file position : ", position)

Current file position :  17


In [10]:
position = fo.seek(0 , 0)
mystr2 = fo.read(17)
print("Again our string is : ", mystr2)

fo.close()

Again our string is :  Python is a great


In [11]:
try:
    fh = open("testfile1301", "r")
    fh.write("This is my test file for exception handling")
    
except IOError:
    print("Error: can\'t find file or read data")
    
else:
    print("Written content in the file successfully")

Error: can't find file or read data


In [13]:
try:
    fh = open("testfile1301", "w")
    fh.write("This is my test file for exception handling")
    fh.close()
    
finally:
    print("This executes anyway")

This executes anyway


In [14]:
print(list('cat'))

['c', 'a', 't']


In [17]:
lst1 = ['physics', 'chemistry', 2017, 2023]
print("Value at index 2 : ", lst1[2]) #zero-based indexing

Value at index 2 :  2017


In [18]:
a_tuple = ('ready', 'fire', 'aim')
print(list(a_tuple))

['ready', 'fire', 'aim']


In [19]:
tup1 = ('physics', 'chemistry', 2017, 2023)
tup2 = (1,2,3,4,5,6,7)
print("tup1[3]: ", tup1[3])
print("tup2[2:6] : ", tup2[2:6])

tup1[3]:  2023
tup2[2:6] :  (3, 4, 5, 6)


In [20]:
mylist = ['python', 'java', 2017, 2023]
print(mylist)
del mylist[1]
print("After deleting value at index 1 : ", mylist)

['python', 'java', 2017, 2023]
After deleting value at index 1 :  ['python', 2017, 2023]


In [21]:
lst2 = ['python', 'geometry', 2017, 2023]
print("Value at index 3 : ", lst2[3])
lst2[3] = 5000
print("New value at index 3 : ", lst2[3])

Value at index 3 :  2023
New value at index 3 :  5000


In [22]:
txt = 'but soft what light in window breaks'
words = txt.split()
print(words)

['but', 'soft', 'what', 'light', 'in', 'window', 'breaks']


In [23]:
pow2 = [2 ** x for x in range(10) if x > 5] #list comprehension
print(pow2)

[64, 128, 256, 512]


In [24]:
pow2 = []
for x in range(10):
    pow2.append(print(2 ** x)) #\n

1
2
4
8
16
32
64
128
256
512


In [25]:
langs = []
langs.append("Python")
langs.append("Perl")
print(langs)

['Python', 'Perl']


In [26]:
langs.insert(0, "PHP")
langs.insert(2, "Lua")
print(langs)

['PHP', 'Python', 'Lua', 'Perl']


In [27]:
langs.extend(("Javascript", "Actionscript"))
print(langs)

['PHP', 'Python', 'Lua', 'Perl', 'Javascript', 'Actionscript']


In [28]:
langs = ["Python", "Ruby", "Perl", "Lua", "Javascript"]
print(langs)

del langs[1]
print(langs)



['Python', 'Ruby', 'Perl', 'Lua', 'Javascript']
['Python', 'Perl', 'Lua', 'Javascript']


In [29]:
del langs[:]
print(langs)

[]


In [30]:
L = ['a', 'b', 'c']
for index, item in enumerate(L):
    print(index, item)

0 a
1 b
2 c


In [31]:
#string birleştirme (concat)

hello = "hello"
python = "python"

print(hello + " " + python)
print("%s %s" % (hello, python))
print("{} {}".format(hello, python))
print(' '.join([hello, python]))

hello python
hello python
hello python
hello python


In [32]:
#bölümleme (slicing)

ss = "Shark attacks fisherman!"

print(ss[:5])
print(ss[7:])
print(ss[-4:-1])
print(ss[0:12:2])

Shark
ttacks fisherman!
man
Sakatc


In [33]:
#lambda, map, reduce, filter

In [34]:
toplama = lambda a : a + 10
print(toplama(5))

15


In [36]:
carpim = lambda a, b : a * b
print(carpim(5, 6))

30


In [37]:
res = (lambda *args : sum(args))
res(10, 20), res(10,20,30,40), res(10,20,30,40,50,60,70)

(30, 100, 280)

In [38]:
res1 = (lambda **kwargs : sum(kwargs.values()))
res1(a = 10, b = 20, c = 30) , res1(a = 10, b = 20, c = 30, d = 40, e = 50)

(60, 150)

In [39]:
list1 = [1,2,3,4,5,6,7,8,9]

def odd(n):
    if n%2 == 1:
        return True
    else:
        return False
    
odd_num = list(filter(odd, list1))
print(odd_num)

[1, 3, 5, 7, 9]


In [40]:
list1 = [1,2,3,4,5,6,7,8,9]
    
odd_num = list(filter(lambda n : n % 2 == 1, list1))
print(odd_num)

[1, 3, 5, 7, 9]


In [41]:
def twice(n):
    return n*2

doubles = list(map(twice, odd_num))
print(doubles)

[2, 6, 10, 14, 18]


In [42]:
doubles = list(map(lambda n: n*2, odd_num))
print(doubles)

[2, 6, 10, 14, 18]


In [43]:
from functools import reduce

def add(a, b):
    return a + b

sum_all = reduce(add, doubles)
print(sum_all)

50


In [44]:
sum_all = reduce(lambda a, b : a + b, doubles)
sum_all

50

In [45]:
from numpy import *
import time
def trad_version ():
    t1 = time . time ()
    X = range (10000000)
    Y = range (10000000)
    Z = []
    for i in range (len (X)):
         Z. append (X[i] + Y[i])
    return time . time () - t1

In [46]:
trad_version()

5.564532518386841

In [47]:
def numpy_version ():
    t1 = time . time ()
    X = arange (10000000)
    Y = arange (10000000)
    Z = X + Y
    return time . time () - t1

In [48]:
numpy_version()

0.06084322929382324

In [52]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [53]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [54]:
type(list1)

list

In [55]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [56]:
arr1.data

In [57]:
type(arr1)

numpy.ndarray

In [58]:
arr1.dtype

dtype('int32')

In [59]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [60]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [62]:
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [63]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [64]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [65]:
np.repeat(10, 5)

array([10, 10, 10, 10, 10])

In [66]:
a = np.array([10,20,30])
np.repeat(a, 3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [67]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [68]:
ar1 = np.arange(1, 20)
ar1[ar1 % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [69]:
ar1 = np.arange(1, 20)
ar1[ar1 % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [70]:
np.linspace(10, 20, 4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [71]:
np.linspace(10,20,11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [72]:
np.random.random(4)

array([0.77856312, 0.3045402 , 0.60676684, 0.69741317])

In [73]:
np.random.randint(0, 500, 5)

array([271, 491, 456, 407, 143])

In [74]:
np.random.randint(0, 500, 10)

array([  2, 234,   3,  70, 282, 135, 149, 195,  57, 331])

In [75]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [76]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [77]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [78]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [80]:
f1 = np.random.uniform(5, 10, size=(10))
f1

array([5.41780717, 8.01774211, 8.64496379, 6.38119414, 8.42653164,
       7.58933737, 5.24242269, 5.68934619, 5.93483713, 9.97158951])

In [81]:
np.floor(f1) #integer part

array([5., 8., 8., 6., 8., 7., 5., 5., 5., 9.])

In [82]:
np.trunc(f1) #decimal part

array([5., 8., 8., 6., 8., 7., 5., 5., 5., 9.])

In [83]:
f1.astype(int)

array([5, 8, 8, 6, 8, 7, 5, 5, 5, 9])

In [84]:
b2 = np.random.randn(10)
b2 #mean, ortalama = 0, variance, değişinti = 1

array([ 2.60596728,  0.68350889,  0.30266545,  1.69372293, -1.70608593,
       -1.15911942, -0.13484072,  0.39052784,  0.16690464,  0.18450186])

In [85]:
arr1

array([10, 20, 30, 40, 50, 60])

In [86]:
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


In [87]:
#numpy dizileri üzerindeki işlemler
arr2 = np.arange(1,20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [88]:
arr2.sum()

190

In [89]:
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [90]:
arr2.min(), arr2.max()

(1, 19)

In [92]:
arr2.argmin(), arr2.argmax()

(0, 18)

In [93]:
arr2.mean()

10.0

In [94]:
np.var(arr2)

30.0

In [95]:
A = np.array([[1,2,3,0], [5,6,7,22], [10,11,1,13], [14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [96]:
A.sum()

129

In [97]:
A.max()

22

In [98]:
A.min()

0

In [99]:
np.amin(A, axis = 0) #sütun bazlı minimum değerler

array([1, 2, 1, 0])

In [100]:
np.amin(A, axis = 1) #satır bazlı minimum değerler

array([0, 5, 1, 3])

In [101]:
A.mean()

8.0625

In [102]:
np.mean(A)

8.0625

In [103]:
np.var(A), np.std(A)

(40.30859375, 6.348904925260734)

In [104]:
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


In [105]:
#eleman okuma
a = np.array([7,5,3,9,2,0])

In [106]:
a[0]

7

In [107]:
a[1:]

array([5, 3, 9, 2, 0])

In [108]:
a[1:4]

array([5, 3, 9])

In [109]:
a[-1]

0

In [110]:
a[-3]

9

In [111]:
a[-6]

7

In [112]:
a[-3:-1]

array([9, 2])