In [2]:
import numpy as np
ar = np.arange(1, 20)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [3]:
rep1 = np.where(ar % 2 == 0, 0, ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [4]:
ar2 = np.array([10, 20, 30, 10, 10, 20, 20])
ar2

array([10, 20, 30, 10, 10, 20, 20])

In [6]:
rep2 = np.where(ar2 == 10, 99, ar2)
print(rep2)

[99 20 30 99 99 20 20]


In [7]:
p2 = np.arange(0, 100, 10)
p2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
np.put(p2, [0, 3, 5], [33, 55, 99])
p2

array([33, 10, 20, 55, 40, 99, 60, 70, 80, 90])

In [9]:
a = np.array([10, np.nan, 20, 30, 60, np.nan, 90, np.inf])
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [10]:
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [11]:
np.where(np.isnan(a))

(array([1, 5], dtype=int64),)

In [12]:
a[np.isnan(a)] = 99
a

array([10., 99., 20., 30., 60., 99., 90., inf])

In [13]:
A = np.array([[1,2,np.nan,4], [np.nan,6,7,8], [10,np.nan,12,13], [14,15,16,17]])
A

array([[ 1.,  2., nan,  4.],
       [nan,  6.,  7.,  8.],
       [10., nan, 12., 13.],
       [14., 15., 16., 17.]])

In [14]:
np.isnan(A)

array([[False, False,  True, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [15]:
np.where(np.isnan(A))

(array([0, 1, 2], dtype=int64), array([2, 0, 1], dtype=int64))

In [16]:
a = np.zeros(20).reshape(2, -1)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
b = np.repeat(1, 20).reshape(2, -1)
b

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [18]:
np.vstack([a,b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
a1 = np.array([[1], [2], [3]])
b1 = np.array([[4], [5], [6]])

In [20]:
a1

array([[1],
       [2],
       [3]])

In [21]:
b1

array([[4],
       [5],
       [6]])

In [22]:
np.vstack([a1, b1])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [23]:
np.hstack([a, b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [24]:
np.hstack([a1, b1])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
c1 = np.array([10,20,30,40,50,60])
c2 = np.array([12,20,33,40,55,60])

In [27]:
np.intersect1d(c1, c2)

array([20, 40, 60])

In [28]:
np.setdiff1d(c1, c2)

array([10, 30, 50])

In [29]:
a = np.array([1,2,3,6,8])
b = np.array([10,2,30,60,8])

np.where(a == b)

(array([1, 4], dtype=int64),)

In [30]:
a[np.where(a == b)]

array([2, 8])

In [31]:
a1 = np.arange(0, 60)
a1[np.where ((a1 > 20) & (a1 < 35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [32]:
a1 = np.arange(0, 60)
a1[np.where (((a1 > 20) & (a1 < 35)) | (a1 % 10 == 0))]

array([ 0, 10, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       40, 50])

In [33]:
a1[np.where(np.logical_and(a1 > 20, a1 < 35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [34]:
a4 = np.arange(10,30)
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [42]:
a4[10:0:-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [39]:
np.flip(a4)

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [43]:
a3 = np.array([[3,2,8,1], [70, 50, 10, 67], [45, 25, 75, 15], [12, 9, 77, 4]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15],
       [12,  9, 77,  4]])

In [44]:
a3[::-1,]

array([[12,  9, 77,  4],
       [45, 25, 75, 15],
       [70, 50, 10, 67],
       [ 3,  2,  8,  1]])

In [45]:
a3[:,::-1]

array([[ 1,  8,  2,  3],
       [67, 10, 50, 70],
       [15, 75, 25, 45],
       [ 4, 77,  9, 12]])

In [46]:
a3[::-1, ::-1]

array([[ 4, 77,  9, 12],
       [15, 75, 25, 45],
       [67, 10, 50, 70],
       [ 1,  8,  2,  3]])

In [47]:
#Sıralama
a = np.array([10, 5, 2, 22, 12, 92, 17, 33])

In [48]:
np.sort(a)

array([ 2,  5, 10, 12, 17, 22, 33, 92])

In [50]:
a3 = np.array([[3,2,8,1], [70, 50, 10, 67], [45, 25, 75,15]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15]])

In [51]:
np.sort(a3)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [52]:
np.sort(a3, axis = 1) #satıra göre sıralama

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [53]:
np.sort(a3, axis = 0) #sütuna göre sıralama

array([[ 3,  2,  8,  1],
       [45, 25, 10, 15],
       [70, 50, 75, 67]])

In [54]:
#Azalan sıraya göre sıralama (büyükten küçüğe sıralama)
b = np.sort(a)
b = b[::-1]
b

array([92, 33, 22, 17, 12, 10,  5,  2])

In [55]:
c = np.sort(a)
np.flip(c)

array([92, 33, 22, 17, 12, 10,  5,  2])

In [56]:
#yükleme (load) ve kaydetme (save) işlemleri, loadtxt ile genfromtxt
p4 = np.loadtxt('sample.txt', dtype = np.integer)
p4

array([[24, 29, 88],
       [ 1,  0,  8],
       [33,  7, 99],
       [39, 11, 98],
       [22, 76, 87]])

In [57]:
p5 = np.genfromtxt('sample0.txt', dtype='str')
p5

array([['Dogu', 'Turkey', 'Football'],
       ['John', 'USA', 'Hockey'],
       ['Paul', 'Canada', 'Basketball']], dtype='<U10')

In [58]:
p5[0]

array(['Dogu', 'Turkey', 'Football'], dtype='<U10')

In [59]:
p5[:,0]

array(['Dogu', 'John', 'Paul'], dtype='<U10')

In [60]:
p8 = np.arange(0,121).reshape(11,11)
p8

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [61]:
np.save('18012022.npy', p8)

In [62]:
p9 = np.load('18012022.npy')
p9

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [63]:
p11 = np.arange(0, 1000000).reshape(1000,1000)
p11

array([[     0,      1,      2, ...,    997,    998,    999],
       [  1000,   1001,   1002, ...,   1997,   1998,   1999],
       [  2000,   2001,   2002, ...,   2997,   2998,   2999],
       ...,
       [997000, 997001, 997002, ..., 997997, 997998, 997999],
       [998000, 998001, 998002, ..., 998997, 998998, 998999],
       [999000, 999001, 999002, ..., 999997, 999998, 999999]])

In [64]:
np.savez_compressed('test18012022.npz', p11)

In [65]:
np.save('test18012022.npy', p11)

In [66]:
#vektör toplama
v1 = np.array([1,2])
v2 = np.array([3,4])
v3 = v1 + v2
print('V3 =', v3)

V3 = [4 6]


In [67]:
v1 = np.array([1,2])
v2 = np.array([3,4])
v3 = np.add(v1, v2)
print('V3 =', v3)

V3 = [4 6]


In [69]:
a1 = np.array([5,6,8])
a2 = np.array([4,7,9])
print(np.multiply(a1,a2))

[20 42 72]


In [70]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

dotp = a1@a2
print("Dot product - ", dotp)

dotp = np.dot(a1, a2)
print("np.dot kullanarak Dot Product - ", dotp)

dotp = np.inner(a1, a2)
print("np.inner kullanarak Dot Product - ", dotp)

dotp = sum(np.multiply(a1,a2))
print("np.multiply & sum kullanarak Dot Product - ", dotp)

dotp = np.matmul(a1, a2)
print("np.matmul kullanarak Dot Product - ", dotp)

dotp = 0
for i in range(len(a1)):
    dotp = dotp + a1[i]*a2[i]
print("döngü kullanarak Dot Product - ", dotp)

Dot product -  32
np.dot kullanarak Dot Product -  32
np.inner kullanarak Dot Product -  32
np.multiply & sum kullanarak Dot Product -  32
np.matmul kullanarak Dot Product -  32
döngü kullanarak Dot Product -  32


In [71]:
v3 = np.array([1,2,3,4,5,6])
length = np.sqrt(np.dot(v3,v3))
length

9.539392014169456

In [72]:
v3 = np.array([1,2,3,4,5,6])
length = np.sqrt(sum(np.multiply(v3,v3)))
length

9.539392014169456

In [73]:
v3 = np.array([1,2,3,4,5,6])
length = np.sqrt(np.matmul(v3,v3))
length

9.539392014169456

In [74]:
#Normalizasyon
v1 = [2,3]
length_v1 = np.sqrt(np.dot(v1,v1))
norm_v1 = v1/length_v1
length_v1, norm_v1

(3.605551275463989, array([0.5547002 , 0.83205029]))

In [75]:
v1 = [2,3]
norm_v1 = v1/np.linalg.norm(v1)
norm_v1

array([0.5547002 , 0.83205029])

In [76]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print("\nVektör Cross Product ==> \n", np.cross(v1,v2))


Vektör Cross Product ==> 
 [-3  6 -3]


In [77]:
I = np.eye(9)
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [78]:
D = np.diag([1,2,3,4,5,6,7,8])
D

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

In [79]:
M = np.random.randn(5,5)
U = np.triu(M) #upper triangle
L = np.tril(M) #lower traingle

print(M)
print("\n")

print(L)
print("\n")

print(U)

[[ 0.47319625  0.64682756 -1.76576466  1.16274986 -0.10486185]
 [ 0.91274386 -1.02366792  0.4705799   0.28760839 -1.92733616]
 [ 0.39680583 -1.34078097 -0.07337397  1.51241921 -1.09599987]
 [-0.08516508 -1.26056588  1.91709455 -0.19335335  0.28284666]
 [-0.33216104 -0.82802135  0.66551242 -0.25451644  0.55293108]]


[[ 0.47319625  0.          0.          0.          0.        ]
 [ 0.91274386 -1.02366792  0.          0.          0.        ]
 [ 0.39680583 -1.34078097 -0.07337397  0.          0.        ]
 [-0.08516508 -1.26056588  1.91709455 -0.19335335  0.        ]
 [-0.33216104 -0.82802135  0.66551242 -0.25451644  0.55293108]]


[[ 0.47319625  0.64682756 -1.76576466  1.16274986 -0.10486185]
 [ 0.         -1.02366792  0.4705799   0.28760839 -1.92733616]
 [ 0.          0.         -0.07337397  1.51241921 -1.09599987]
 [ 0.          0.          0.         -0.19335335  0.28284666]
 [ 0.          0.          0.          0.          0.55293108]]


In [80]:
A

array([[ 1.,  2., nan,  4.],
       [nan,  6.,  7.,  8.],
       [10., nan, 12., 13.],
       [14., 15., 16., 17.]])

In [81]:
A.flatten()

array([ 1.,  2., nan,  4., nan,  6.,  7.,  8., 10., nan, 12., 13., 14.,
       15., 16., 17.])

In [82]:
A.ravel()

array([ 1.,  2., nan,  4., nan,  6.,  7.,  8., 10., nan, 12., 13., 14.,
       15., 16., 17.])

In [83]:
M = np.array([[1,2,3], [4,-3,6], [7,8,0]])

print("\n Matrix(M) --> \n", M)

print("\n Transpose(M) --> \n", np.transpose(M))


 Matrix(M) --> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Transpose(M) --> 
 [[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]


In [84]:
print("\n Transpose(M) --> \n", M.T)


 Transpose(M) --> 
 [[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]


In [87]:
print("\nRank(M) --> ", np.linalg.matrix_rank(M))


Rank(M) -->  3


In [88]:
print("\nInverse(M) --> ", np.linalg.inv(M))


Inverse(M) -->  [[-0.24615385  0.12307692  0.10769231]
 [ 0.21538462 -0.10769231  0.03076923]
 [ 0.27179487  0.03076923 -0.05641026]]


In [90]:
T1 = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[10,20,30], [40,50,60], [70, 80, 90]],
    [[100,200,300], [400,500,600], [700,800,900]],
])

T1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])