In [2]:
"""
scipy.linalg -> LC, denklem çözümü, özdeğer-özvektör hesabı, LU ayrışması (decomposition)
scipy.special -> elliptic, gamma, beta, hypergeometric, kelvin, parabolic cylinder
scipy.integrate -> 
scipy.optimize
scipy.interpolate
scipy.fftpack
scipy.signal
spatial veri yapıları ve algoritmaları - scipy.spatial
scipy.stats
scipy.ndimage
scipy.io
"""

'\nscipy.linalg -> LC, denklem çözümü, özdeğer-özvektör hesabı, LU ayrışması (decomposition)\nscipy.special -> elliptic, gamma, beta, hypergeometric, kelvin, parabolic cylinder\nscipy.integrate -> \nscipy.optimize\nscipy.interpolate\nscipy.fftpack\nscipy.signal\nspatial veri yapıları ve algoritmaları - scipy.spatial\nscipy.stats\nscipy.ndimage\nscipy.io\n'

In [3]:
import numpy as np
from scipy import linalg
A = np.array([[1,2], [3,4]])
print(A)
B = linalg.inv(A)
print(B)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [4]:
import numpy as np
from scipy import linalg
A = np.array([[1,2], [3,4]])
print(A)
print(A.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [5]:
A = np.array([[1,3,5], [2,5,1], [2,3,8]])
print(A)
b = np.array([[10], [8], [3]])
print(b)
print("inv ve dot ile denklem çözümü :")
print(linalg.inv(A).dot(b)) #yavaş çözüm
print("solve ile denklem çözümü :")
print(np.linalg.solve(A, b)) #hızlı çözüm

[[1 3 5]
 [2 5 1]
 [2 3 8]]
[[10]
 [ 8]
 [ 3]]
inv ve dot ile denklem çözümü :
[[-9.28]
 [ 5.16]
 [ 0.76]]
solve ile denklem çözümü :
[[-9.28]
 [ 5.16]
 [ 0.76]]


In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import math
import warnings
warnings.filterwarnings("ignore")

In [7]:
#Seriler
v = np.array([1,2,3,4,5,6,7])
s1 = pd.Series(v)
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32

In [8]:
s1.dtype

dtype('int32')

In [9]:
s1.nbytes

28

In [10]:
s1.shape

(7,)

In [11]:
s0 = pd.Series([1,2,3], index = ['a', 'b' , 'c'])
s0

a    1
b    2
c    3
dtype: int64

In [12]:
s1.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
s1

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [13]:
v2 = np.random.random(10)
ind2 = np.arange(0, 10)
s = pd.Series(v2, ind2)
v2, ind2, s

(array([0.66803803, 0.14578183, 0.40566317, 0.0603406 , 0.14647377,
        0.20257302, 0.98199253, 0.73214233, 0.29714017, 0.21201563]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 0    0.668038
 1    0.145782
 2    0.405663
 3    0.060341
 4    0.146474
 5    0.202573
 6    0.981993
 7    0.732142
 8    0.297140
 9    0.212016
 dtype: float64)

In [14]:
dict1 = {'a1' : 10, 'a2' : 20, 'a3' : 30, 'a4': 40}
s3 = pd.Series(dict1)
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [15]:
pd.Series(99, index = [0,1,2,3,4,5])

0    99
1    99
2    99
3    99
4    99
5    99
dtype: int64

In [16]:
s

0    0.668038
1    0.145782
2    0.405663
3    0.060341
4    0.146474
5    0.202573
6    0.981993
7    0.732142
8    0.297140
9    0.212016
dtype: float64

In [17]:
s[:]

0    0.668038
1    0.145782
2    0.405663
3    0.060341
4    0.146474
5    0.202573
6    0.981993
7    0.732142
8    0.297140
9    0.212016
dtype: float64

In [18]:
s[0:3]

0    0.668038
1    0.145782
2    0.405663
dtype: float64

In [19]:
s[-1:]

9    0.212016
dtype: float64

In [20]:
s[:4]

0    0.668038
1    0.145782
2    0.405663
3    0.060341
dtype: float64

In [21]:
s2 = s1.copy()
s2

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [22]:
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [23]:
s4 = s2.append(s3)
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [26]:
s4.drop('a4', inplace = True)

In [27]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [28]:
s4 = s4.append(pd.Series({'a4':7}))
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4     7
dtype: int64

In [29]:
v1 = np.array([10,20,30])
v2 = np.array([1,2,3])
s1 = pd.Series(v1)
s2 = pd.Series(v2)
s1 ,s2

(0    10
 1    20
 2    30
 dtype: int32,
 0    1
 1    2
 2    3
 dtype: int32)

In [30]:
s1.add(s2)

0    11
1    22
2    33
dtype: int32

In [31]:
s1.sub(s2)

0     9
1    18
2    27
dtype: int32

In [33]:
s1.subtract(s2)

0     9
1    18
2    27
dtype: int32

In [34]:
s1.add(9)

0    19
1    29
2    39
dtype: int32

In [35]:
s1.mul(s2)

0    10
1    40
2    90
dtype: int32

In [36]:
s1.multiply(s2)

0    10
1    40
2    90
dtype: int32

In [37]:
s1.multiply(1000)

0    10000
1    20000
2    30000
dtype: int32

In [38]:
s1.divide(s2)

0    10.0
1    10.0
2    10.0
dtype: float64

In [39]:
s1.min()

10

In [40]:
s1.mean()

20.0

In [41]:
s1.std()

10.0

In [42]:
s1.equals(s2)

False

In [43]:
#Dataframes

In [45]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [46]:
lang = ['Java', 'Python', 'C', 'C++']
df = pd.DataFrame(lang)
df

0
0    Java
1  Python
2       C
3     C++

In [47]:
rating = [1,2,3,4]
df[1] = rating
df

0  1
0    Java  1
1  Python  2
2       C  3
3     C++  4

In [48]:
df.columns = ['Language', 'Rating']

In [49]:
df

Language  Rating
0     Java       1
1   Python       2
2        C       3
3      C++       4

In [50]:
data = [{'a':1, 'b':2}, {'a':5, 'b':10, 'c':20}]

df2 = pd.DataFrame(data)

In [51]:
df2

a   b     c
0  1   2   NaN
1  5  10  20.0

In [52]:
df3 = pd.DataFrame(data, index=['row1','row2'], columns=['a', 'b'])
df4 = pd.DataFrame(data, index=['row1','row2'], columns=['a', 'b', 'c'])
df5 = pd.DataFrame(data, index=['row1','row2'], columns=['a', 'b', 'c', 'd'])

In [53]:
df3

a   b
row1  1   2
row2  5  10

In [54]:
df4

a   b     c
row1  1   2   NaN
row2  5  10  20.0

In [55]:
df5

a   b     c   d
row1  1   2   NaN NaN
row2  5  10  20.0 NaN

In [56]:
dates = pd.date_range(start='2022-01-20', end='2022-01-26')
dates

DatetimeIndex(['2022-01-20', '2022-01-21', '2022-01-22', '2022-01-23',
               '2022-01-24', '2022-01-25', '2022-01-26'],
              dtype='datetime64[ns]', freq='D')

In [57]:
dates = pd.date_range('today', periods = 7)

In [58]:
dates

DatetimeIndex(['2022-01-20 22:19:07.206449', '2022-01-21 22:19:07.206449',
               '2022-01-22 22:19:07.206449', '2022-01-23 22:19:07.206449',
               '2022-01-24 22:19:07.206449', '2022-01-25 22:19:07.206449',
               '2022-01-26 22:19:07.206449'],
              dtype='datetime64[ns]', freq='D')

In [62]:
dates = pd.date_range(start='2022-01-20', periods = 7)

In [63]:
M = np.random.random((7,7))
M

array([[0.79608764, 0.530132  , 0.67455604, 0.66724241, 0.29135817,
        0.90975229, 0.56090313],
       [0.44898317, 0.02312029, 0.40311812, 0.30255233, 0.45830142,
        0.83645541, 0.962075  ],
       [0.21523801, 0.22471958, 0.42806658, 0.44175046, 0.004185  ,
        0.43501961, 0.0757473 ],
       [0.13684259, 0.02904662, 0.03766746, 0.13286441, 0.25779503,
        0.36588638, 0.35720605],
       [0.0548565 , 0.2951299 , 0.72232803, 0.1389688 , 0.51347994,
        0.66111054, 0.56917024],
       [0.36039618, 0.95768989, 0.05532944, 0.99523436, 0.79698956,
        0.88859499, 0.5749415 ],
       [0.02370925, 0.01732421, 0.64201836, 0.8749702 , 0.69275   ,
        0.67962308, 0.32636494]])

In [64]:
dframe = pd.DataFrame(M, index = dates)
dframe

0         1         2         3         4         5  \
2022-01-20  0.796088  0.530132  0.674556  0.667242  0.291358  0.909752   
2022-01-21  0.448983  0.023120  0.403118  0.302552  0.458301  0.836455   
2022-01-22  0.215238  0.224720  0.428067  0.441750  0.004185  0.435020   
2022-01-23  0.136843  0.029047  0.037667  0.132864  0.257795  0.365886   
2022-01-24  0.054856  0.295130  0.722328  0.138969  0.513480  0.661111   
2022-01-25  0.360396  0.957690  0.055329  0.995234  0.796990  0.888595   
2022-01-26  0.023709  0.017324  0.642018  0.874970  0.692750  0.679623   

                   6  
2022-01-20  0.560903  
2022-01-21  0.962075  
2022-01-22  0.075747  
2022-01-23  0.357206  
2022-01-24  0.569170  
2022-01-25  0.574941  
2022-01-26  0.326365

In [66]:
dframe.columns = ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7']
dframe

C1        C2        C3        C4        C5        C6  \
2022-01-20  0.796088  0.530132  0.674556  0.667242  0.291358  0.909752   
2022-01-21  0.448983  0.023120  0.403118  0.302552  0.458301  0.836455   
2022-01-22  0.215238  0.224720  0.428067  0.441750  0.004185  0.435020   
2022-01-23  0.136843  0.029047  0.037667  0.132864  0.257795  0.365886   
2022-01-24  0.054856  0.295130  0.722328  0.138969  0.513480  0.661111   
2022-01-25  0.360396  0.957690  0.055329  0.995234  0.796990  0.888595   
2022-01-26  0.023709  0.017324  0.642018  0.874970  0.692750  0.679623   

                  C7  
2022-01-20  0.560903  
2022-01-21  0.962075  
2022-01-22  0.075747  
2022-01-23  0.357206  
2022-01-24  0.569170  
2022-01-25  0.574941  
2022-01-26  0.326365

In [67]:
dframe.index

DatetimeIndex(['2022-01-20', '2022-01-21', '2022-01-22', '2022-01-23',
               '2022-01-24', '2022-01-25', '2022-01-26'],
              dtype='datetime64[ns]', freq='D')

In [68]:
dframe.sort_values(by='C1')

C1        C2        C3        C4        C5        C6  \
2022-01-26  0.023709  0.017324  0.642018  0.874970  0.692750  0.679623   
2022-01-24  0.054856  0.295130  0.722328  0.138969  0.513480  0.661111   
2022-01-23  0.136843  0.029047  0.037667  0.132864  0.257795  0.365886   
2022-01-22  0.215238  0.224720  0.428067  0.441750  0.004185  0.435020   
2022-01-25  0.360396  0.957690  0.055329  0.995234  0.796990  0.888595   
2022-01-21  0.448983  0.023120  0.403118  0.302552  0.458301  0.836455   
2022-01-20  0.796088  0.530132  0.674556  0.667242  0.291358  0.909752   

                  C7  
2022-01-26  0.326365  
2022-01-24  0.569170  
2022-01-23  0.357206  
2022-01-22  0.075747  
2022-01-25  0.574941  
2022-01-21  0.962075  
2022-01-20  0.560903

In [69]:
dframe.sort_values(by='C1', ascending = False)

C1        C2        C3        C4        C5        C6  \
2022-01-20  0.796088  0.530132  0.674556  0.667242  0.291358  0.909752   
2022-01-21  0.448983  0.023120  0.403118  0.302552  0.458301  0.836455   
2022-01-25  0.360396  0.957690  0.055329  0.995234  0.796990  0.888595   
2022-01-22  0.215238  0.224720  0.428067  0.441750  0.004185  0.435020   
2022-01-23  0.136843  0.029047  0.037667  0.132864  0.257795  0.365886   
2022-01-24  0.054856  0.295130  0.722328  0.138969  0.513480  0.661111   
2022-01-26  0.023709  0.017324  0.642018  0.874970  0.692750  0.679623   

                  C7  
2022-01-20  0.560903  
2022-01-21  0.962075  
2022-01-25  0.574941  
2022-01-22  0.075747  
2022-01-23  0.357206  
2022-01-24  0.569170  
2022-01-26  0.326365

In [71]:
df2 #Sütun silme

a   b     c
0  1   2   NaN
1  5  10  20.0

In [72]:
del df2['b']

In [73]:
df2

a     c
0  1   NaN
1  5  20.0

In [74]:
del df2['c']

In [75]:
df2

a
0  1
1  5

In [76]:
df3

a   b
row1  1   2
row2  5  10

In [77]:
df3.pop('b')

row1     2
row2    10
Name: b, dtype: int64

In [78]:
dict = {'A' : pd.Series([1,2,3,11], index=['a', 'b', 'c', 'd']),
        'B' : pd.Series([1,2,3,4], index=['a', 'b', 'c', 'd'])}

df12 = pd.DataFrame(dict)
df12

A  B
a   1  1
b   2  2
c   3  3
d  11  4

In [79]:
df12.drop(['A'], axis = 1, inplace = True)
df12

B
a  1
b  2
c  3
d  4

In [80]:
col1 = np.linspace(10,100,30)
col2 = np.random.randint(10,100,30)
df10 = pd.DataFrame({"C1":col1, "C2":col2})
df10

C1  C2
0    10.000000  85
1    13.103448  79
2    16.206897  48
3    19.310345  61
4    22.413793  96
5    25.517241  89
6    28.620690  27
7    31.724138  32
8    34.827586  97
9    37.931034  75
10   41.034483  13
11   44.137931  83
12   47.241379  15
13   50.344828  77
14   53.448276  19
15   56.551724  96
16   59.655172  61
17   62.758621  14
18   65.862069  45
19   68.965517  49
20   72.068966  69
21   75.172414  78
22   78.275862  69
23   81.379310  15
24   84.482759  14
25   87.586207  93
26   90.689655  90
27   93.793103  31
28   96.896552  59
29  100.000000  70

In [81]:
df10 = df10.drop([17,18,19], axis = 0)
df10

C1  C2
0    10.000000  85
1    13.103448  79
2    16.206897  48
3    19.310345  61
4    22.413793  96
5    25.517241  89
6    28.620690  27
7    31.724138  32
8    34.827586  97
9    37.931034  75
10   41.034483  13
11   44.137931  83
12   47.241379  15
13   50.344828  77
14   53.448276  19
15   56.551724  96
16   59.655172  61
20   72.068966  69
21   75.172414  78
22   78.275862  69
23   81.379310  15
24   84.482759  14
25   87.586207  93
26   90.689655  90
27   93.793103  31
28   96.896552  59
29  100.000000  70

In [82]:
df10.drop([16], axis = 0, inplace = True)
df10

C1  C2
0    10.000000  85
1    13.103448  79
2    16.206897  48
3    19.310345  61
4    22.413793  96
5    25.517241  89
6    28.620690  27
7    31.724138  32
8    34.827586  97
9    37.931034  75
10   41.034483  13
11   44.137931  83
12   47.241379  15
13   50.344828  77
14   53.448276  19
15   56.551724  96
20   72.068966  69
21   75.172414  78
22   78.275862  69
23   81.379310  15
24   84.482759  14
25   87.586207  93
26   90.689655  90
27   93.793103  31
28   96.896552  59
29  100.000000  70

In [83]:
df10.drop(df10.index[5], inplace = True)

In [84]:
df10

C1  C2
0    10.000000  85
1    13.103448  79
2    16.206897  48
3    19.310345  61
4    22.413793  96
6    28.620690  27
7    31.724138  32
8    34.827586  97
9    37.931034  75
10   41.034483  13
11   44.137931  83
12   47.241379  15
13   50.344828  77
14   53.448276  19
15   56.551724  96
20   72.068966  69
21   75.172414  78
22   78.275862  69
23   81.379310  15
24   84.482759  14
25   87.586207  93
26   90.689655  90
27   93.793103  31
28   96.896552  59
29  100.000000  70

In [85]:
df10 = df10.iloc[3:,]
df10

C1  C2
3    19.310345  61
4    22.413793  96
6    28.620690  27
7    31.724138  32
8    34.827586  97
9    37.931034  75
10   41.034483  13
11   44.137931  83
12   47.241379  15
13   50.344828  77
14   53.448276  19
15   56.551724  96
20   72.068966  69
21   75.172414  78
22   78.275862  69
23   81.379310  15
24   84.482759  14
25   87.586207  93
26   90.689655  90
27   93.793103  31
28   96.896552  59
29  100.000000  70

In [86]:
df10 = df10.iloc[:-4,]

In [87]:
df10

C1  C2
3   19.310345  61
4   22.413793  96
6   28.620690  27
7   31.724138  32
8   34.827586  97
9   37.931034  75
10  41.034483  13
11  44.137931  83
12  47.241379  15
13  50.344828  77
14  53.448276  19
15  56.551724  96
20  72.068966  69
21  75.172414  78
22  78.275862  69
23  81.379310  15
24  84.482759  14
25  87.586207  93

In [88]:
df10.index[df10['C2'] == 96].tolist()

[4, 15]

In [89]:
df10.drop(df10.index[df10['C2'] == 96].tolist(), axis = 0, inplace = True)
df10

C1  C2
3   19.310345  61
6   28.620690  27
7   31.724138  32
8   34.827586  97
9   37.931034  75
10  41.034483  13
11  44.137931  83
12  47.241379  15
13  50.344828  77
14  53.448276  19
20  72.068966  69
21  75.172414  78
22  78.275862  69
23  81.379310  15
24  84.482759  14
25  87.586207  93

In [90]:
df10 = df10.drop(df10[df10['C2']==77].index)

In [91]:
df10

C1  C2
3   19.310345  61
6   28.620690  27
7   31.724138  32
8   34.827586  97
9   37.931034  75
10  41.034483  13
11  44.137931  83
12  47.241379  15
14  53.448276  19
20  72.068966  69
21  75.172414  78
22  78.275862  69
23  81.379310  15
24  84.482759  14
25  87.586207  93

In [92]:
df #Veri seçme

Language  Rating
0     Java       1
1   Python       2
2        C       3
3      C++       4

In [93]:
df.index = [1,2,3,4]
df

Language  Rating
1     Java       1
2   Python       2
3        C       3
4      C++       4

In [94]:
df.loc[1]

Language    Java
Rating         1
Name: 1, dtype: object

In [95]:
df.iloc[1]

Language    Python
Rating           2
Name: 2, dtype: object

In [96]:
df.loc[1:2]

Language  Rating
1     Java       1
2   Python       2

In [97]:
df.iloc[1:2]

Language  Rating
2   Python       2

In [98]:
df.loc[df.Rating > 2]

Language  Rating
3        C       3
4      C++       4

In [100]:
df2

a
0  1
1  5

In [101]:
df2.loc[0]

a    1
Name: 0, dtype: int64

In [102]:
df.iloc['a'] #iloc etiketler üzerinde çalışmaz!!!!

TypeError: Cannot index by location index with a non-integer key

In [103]:
dframe

C1        C2        C3        C4        C5        C6  \
2022-01-20  0.796088  0.530132  0.674556  0.667242  0.291358  0.909752   
2022-01-21  0.448983  0.023120  0.403118  0.302552  0.458301  0.836455   
2022-01-22  0.215238  0.224720  0.428067  0.441750  0.004185  0.435020   
2022-01-23  0.136843  0.029047  0.037667  0.132864  0.257795  0.365886   
2022-01-24  0.054856  0.295130  0.722328  0.138969  0.513480  0.661111   
2022-01-25  0.360396  0.957690  0.055329  0.995234  0.796990  0.888595   
2022-01-26  0.023709  0.017324  0.642018  0.874970  0.692750  0.679623   

                  C7  
2022-01-20  0.560903  
2022-01-21  0.962075  
2022-01-22  0.075747  
2022-01-23  0.357206  
2022-01-24  0.569170  
2022-01-25  0.574941  
2022-01-26  0.326365

In [104]:
dframe['2022-01-20':'2022-01-22']

C1        C2        C3        C4        C5        C6  \
2022-01-20  0.796088  0.530132  0.674556  0.667242  0.291358  0.909752   
2022-01-21  0.448983  0.023120  0.403118  0.302552  0.458301  0.836455   
2022-01-22  0.215238  0.224720  0.428067  0.441750  0.004185  0.435020   

                  C7  
2022-01-20  0.560903  
2022-01-21  0.962075  
2022-01-22  0.075747

In [105]:
dframe.loc[:, ['C1', 'C7']]

C1        C7
2022-01-20  0.796088  0.560903
2022-01-21  0.448983  0.962075
2022-01-22  0.215238  0.075747
2022-01-23  0.136843  0.357206
2022-01-24  0.054856  0.569170
2022-01-25  0.360396  0.574941
2022-01-26  0.023709  0.326365

In [106]:
dframe.loc['2022-01-20':'2022-01-22', ['C1', 'C7']]

C1        C7
2022-01-20  0.796088  0.560903
2022-01-21  0.448983  0.962075
2022-01-22  0.215238  0.075747

In [107]:
dframe[dframe['C1'] > 0.5]

C1        C2        C3        C4        C5        C6  \
2022-01-20  0.796088  0.530132  0.674556  0.667242  0.291358  0.909752   

                  C7  
2022-01-20  0.560903

In [109]:
dframe[(dframe['C1'] > 0.5) & (dframe['C4'] > 0.5)]

C1        C2        C3        C4        C5        C6  \
2022-01-20  0.796088  0.530132  0.674556  0.667242  0.291358  0.909752   

                  C7  
2022-01-20  0.560903

In [110]:
dframe.iloc[0][0]

0.7960876434339726

In [111]:
dframe.iloc[:,0:3]

C1        C2        C3
2022-01-20  0.796088  0.530132  0.674556
2022-01-21  0.448983  0.023120  0.403118
2022-01-22  0.215238  0.224720  0.428067
2022-01-23  0.136843  0.029047  0.037667
2022-01-24  0.054856  0.295130  0.722328
2022-01-25  0.360396  0.957690  0.055329
2022-01-26  0.023709  0.017324  0.642018

In [112]:
dframe.iloc[0][0] = 10
dframe[dframe['C1'].isin([10,20])]

C1        C2        C3        C4        C5        C6        C7
2022-01-20  10.0  0.530132  0.674556  0.667242  0.291358  0.909752  0.560903